brainstormforce/ultimate-addons-for-gutenberg

classes/class-uagb-helper.php

* Fix notices and json error with FacetWP plugin

resolve notices and facetwp json error

---

classes/class-uagb-helper.php
readme.txt

* Fix notices and json error with FacetWP plugin

Fix: json error with facetwp

---

classes/class-uagb-init-blocks.php
readme.txt

- Added version number to script.

Js version no

---

classes/class-uagb-loader.php
languages/ultimate-addons-for-gutenberg.pot
readme.txt
ultimate-addons-for-gutenberg.php

* mo file open_basedir restriction issue fixed

Fix: mo file open_basedir restriction fix

---

dist/blocks/post/index.php

Fix: columns not working

---

dist/blocks/post/index.php
readme.txt

Fix: Post Carousel slider not working.

Resolve slide not working

---

Gruntfile.js
README.md
package-lock.json
package.json

* Added  "grunt-wp-readme-to-markdown" for converting readme.txt to readme.md

added grunt read me to generate readme.md file

---

dist/blocks.commoneditorstyle.build.css

* Fix: responsive typography button not clickable

Fix: responsive typography button not clickable

---

classes/class-uagb-block-helper.php

- Fixed: Gravity from CSS not applied to fronted.

Gravity fix

---

classes/class-uagb-admin.php

Arbitrary file include

---

classes/class-uagb-block-helper.php
readme.txt

Added filter `uagb_testimonials_slick_options` to change the slick options.

Add slick filter

---

classes/class-uagb-block-helper.php
readme.txt

* Fix: Broken CSS getting generated for Advanced Column and Section issue fixed.

* Fix: Broken CSS getting generated for Advanced Column and Section

---

classes/class-uagb-helper.php
readme.txt

* Fix: Marketing Button - Background Color and Background Hover Color opacity issue fixed.

* Fix: Marketing Button - Background Color and Background Hover Color opacity issue fixed.

---

classes/class-uagb-init-blocks.php
readme.txt

* Fix: Contact Form 7 Styler - Unregistered console error for certain case scenario issue.
* Fix: Gravity Forms Styler - Unregistered console error for certain case scenario issue.

Unregistered console error for certain case scenario - Contact Form stylers

---

classes/class-uagb-block-helper.php

Need to set values for `icon_bg_color` and `icon_bg_hover_color` for when the user clicked on Clear

Issue #88 - Cater for user clearing an icon's background colours

---

classes/class-uagb-admin.php

Added Rank Math's Compatibility so the plugin can detect the TOC added by your plugin.

Added Rank Math's Compatibility

---

assets/css/slick.css

Fix: Post Carousel - Carousel dots font family issue with OceanWP theme

* Fix: Post Carousel - Carousel dots font family issue with OceanWP theme

---

dist/blocks/post/index.php

I created this filter-call to conditionally show the author depending on whether it's a local author or a link to another blog. In the case of the latter, we're not showing the author details. Therefore, I'm using the filter to set the 'displayPostAuthor' to false.
Hopefully, this is useful to you!

New filter

---

classes/class-uagb-block-helper.php

Changed tabletPaddingType -> mobilePaddingType and tabletMarginType -> mobileMarginType & vice versa

Corrects padding/margin types for tablet/mobile

---

classes/class-uagb-block-helper.php
classes/class-uagb-helper.php
classes/class-uagb-init-blocks.php
composer.json
composer.lock

Completed PHPCS of following files:
1. /classes/class-uagb-block-helper.php
2. /classes/class-uagb-init-blocks.php
3. /classes/class-uagb-helper.php

Improvement: Completed phpcs as per WP 5.3 compatibility

---

classes/class-uagb-helper.php

Fix: Undefined constant FS_CHMOD_FILE issue.

Fix: Undefined constant FS_CHMOD_FILE issue.

---

classes/class-uagb-helper.php
readme.txt

Improvement: Used local variable where get_filesystem() is called more than once.

Improvement: Used local variable where get_filesystem() is called more than once.

---

README.md
dist/blocks.commoneditorstyle.build.css
readme.txt

-Added css to clickable percentage btn in ad column.

Percentage btn not clickable

---

admin/assets/admin-menu-settings.js
readme.txt

Fix: 403 error on Astra activation.

Fix: 403 error on Astra activation.

---

assets/js/table-of-contents.js
readme.txt

Fix: Table of Contents - Support Single and Double quotes in heading.

Fix: Table of Contents - Support Single and Double quotes in heading.

---

classes/class-uagb-helper.php
dist/blocks/post/index.php

Fixed the Pagination issue caused due to Pretty Permalinks.
Bugfix (non-breaking change which fixes an issue)
- Check by using Post Grid Block on the Post and Page and see if the Pagination works.
- Check by changing the Permalink Structure to different structures and see if Pagination works.

Fixed the Pagination issue caused due to Pretty Permalinks.

---

admin/uagb-general.php

Changed the Knowledge Base URL.
https://share.getcloudapp.com/jkulYnd7
Changed URL

Changed the Knowledge Base URL.

---

dist/blocks/post-timeline/index.php
wpml-config.xml

This PR updates the WPML XML file to match the new child blocks
Bugfix (non-breaking change which fixes an issue)

chore: updated WPML XML

---

wpml-config.xml

fix: Updated WPML XML

---

assets/js/faq.js

Fix - All issues in IE browser and the First close issue.
Bug fix (non-breaking change which fixes an issue) 
In IE as well as Chrome.

Fix - All issues in IE browser and the First close issue.

---

assets/js/post.js

Trello Task - https://trello.com/c/SyE8dfF0/66-pagination
Bugfix (non-breaking change which fixes an issue)
- Add multiple Post Masonry Blocks on a Page and set Button Pagination to all and check.

 - Fix issues in Post Masonry Pagination.

---

assets/js/faq.js
dist/blocks.editor.build.css
dist/blocks.style.build.css
readme.txt

Allow links to be clickable within FAQ sections.
Bug fix (non-breaking change which fixes an issue).
- Click on the Ans tab should be FAQ open.
- Click on the Question tab FAQ should be close.
- Click on the link it should be open.

fix: Clicking on answer collapsed the faq.

---

README.md
admin/uagb-general.php
readme.txt

Change Active installation count to 1,000,000+.
- Check the UAGB Setting page.

Fix: Updated active installation to 1,000,000+

---

README.md
readme.txt

Changelog update for 
1. Inline notice issue
1. Language option added in maps
1. FAQ Schema block responsive

Changelog Updated

---

README.md
dist/blocks/post/class-uagb-post.php
readme.txt

- Infinite Scroll Broken for Anonymous User
- Drag and drop post masonry on-page.
- Open page in incognito mode and check infinite scroll.

Infinite scroll issue for logout user

---

README.md
readme.txt

- Updated tested-up to tag WP 5.6
- No breaking change
- check readme and README.md.

Updated tested-up to tag WP 5.6

---

README.md
classes/class-uagb-block-js.php
readme.txt

Trello - https://trello.com/c/YBHy1R6b/174-testimonial-issue-on-rtl-website
- Switch to rtl and check is it visible or not.

Fix: Testinomial - Fixed carousel not being displayed on RTL websites.

---

README.md
classes/class-uagb-config.php
readme.txt

- Updated description in editor and added Lottie section in readme.
- Non breaking change.
- Check readme and description of Lottie in editor.

Added Lottie section in readme and updated description.

---

classes/class-uagb-config.php

- Trello - https://trello.com/c/tuFkguWG/178-imgposition-undefined-issue
- Drag and drop post block and check frontend.

Fix: imgPosition undefined issue in post layout.

---

phpcs.xml.dist

chore: Update phpcs.xml.dist

---

composer.json

chore: Update composer.json

---

.github/workflows/phpcs.yml

chore: Setup GitHub action for PHPCS check.

chore: Setup GitHub action for PHPCS check.

---

.github/workflows/asset-size-check.yml

Added a workflow to check assets size on PR

Assets size check on PR workflow added

---

classes/class-uagb-block-helper.php
classes/class-uagb-config.php
classes/class-uagb-helper.php

- Task - https://trello.com/c/AazLVssY/265-static-css-optimization-block-specific-loading
- Added in Task.

feat: Added new Logic to add Static CSS for Blocks.

---

.distignore
.github/workflows/build-a-zip.yml
bin/build-zip.sh
package.json

Build a zip and comment a link on PR
Non-breaking change

Zip workflow

---

dist/build/blocks.asset.php
src/blocks/forms/settings.js
webpack.config.js

- Added an alias for the components.

fix: Added alias for the components

---

.distignore
.gitattributes
Gruntfile.js
dist/blocks.asset.php
src/blocks/advanced-heading/block.js
src/blocks/blockquote/block.js

Advanced Heading & Blockquotes title updated
Non-breaking change

Advanced Heading & Blockquotes title updated

---

README.md
admin/assets/admin-menu-settings.js
classes/class-uagb-admin.php
classes/class-uagb-config.php
package-lock.json
readme.txt

Reverts brainstormforce/ultimate-addons-for-gutenberg#577

Revert "Fix: Blocks throwing an error when deactivate all the UAG blocks except the `HowTo Schema` and `Multi Buttons`."

---

classes/class-uagb-admin.php

Updated user capabilities as per need.
- Check Rollback & Beta Updated features.

fix: Updated user capabilities as per need.

---

classes/class-uagb-helper.php

fix: Added deprecated functions notice & handled backward compatibility.
- All the deprecated functions used in 3rd party themes/plugins should work as it is.

fix: Added deprecated functions notice & handled backward compatibility.

---

README.md
admin/assets/common-block-editor.css
classes/class-uagb-block-helper.php
dist/blocks.asset.php
readme.txt
src/blocks/table-of-contents/styling.js

- trello - https://trello.com/c/3KATJk0i/325-v1230-testing
- Bug fixes
- CSS breaks for typography when Gutenberg is activated. [https://share.getcloudapp.com/04uABZ7j]
- List margin not working in editor & front-end. [https://share.getcloudapp.com/p9ub1mlW]

Fix: Minor fixes reported by QA in package testing.

---

classes/class-uagb-post-assets.php

- Caching the Google fonts to load.
- Check Font functionality for blocks.

fix: Cache the Google Fonts.

---

classes/class-uagb-admin.php
classes/class-uagb-core-plugin.php
classes/class-uagb-frontend.php
classes/class-uagb-helper.php
classes/class-uagb-loader.php
classes/class-uagb-post-assets.php
classes/class-uagb-scripts-utils.php
classes/class-uagb-twenty-seventeen-compatibility.php

- Trello task - https://trello.com/c/ml5spPU0/329-new-api-for-3rd-party-plugins-to-load-page-assets-by-post-id
New feature (non-breaking change which adds functionality)
- Test Cases in the Card.

Updated assets logic & deprecation functions updated

---

classes/class-uagb-core-plugin.php
classes/class-uagb-frontend.php
classes/class-uagb-init-blocks.php
classes/class-uagb-post-assets.php

- Trello task - https://trello.com/c/ml5spPU0/329-new-api-for-3rd-party-plugins-to-load-page-assets-by-post-id
New feature (non-breaking change which adds functionality
- Added test cases in the Trello card.

new: API for 3rd Party Plugins to load Page assets by Post ID.

---

admin/assets/admin-menu-settings.js
admin/uagb-general.php
classes/class-uagb-admin.php
classes/class-uagb-scripts-utils.php
dist/blocks.asset.php
src/blocks/how-to/edit.js
src/blocks/how-to/schema-notices.js

- Trello task - https://trello.com/c/npBgSX79/288-fix-blocks-throwing-an-error-when-activate-only-forms-or-multi-buttons
- Deactivate Info Box in master.
- Switch to the current branch.
- Keep HTML notice on infobox
- Editor will work without error

Deactivated InfoBox Block was throwing error in editor

---

classes/class-uagb-helper.php

fix: Declared & Updated as deprecated the class variables for Backward compatibility.
- Check for any Fatal errors.

fix: Declared & Updated as deprecated the class variables for Backward compatibility.

---

README.md
assets/js/table-of-contents.js
blocks-config/table-of-content/class-uagb-table-of-content.php
classes/class-uagb-loader.php
package-lock.json
package.json
readme.txt
ultimate-addons-for-gutenberg.php

- Trello - https://trello.com/c/hOLRAVBZ/365-fix-table-of-contents-heading-replaced-with-the-question-symbol
- Create a page with heading in Hindi/Bengali and non-latin language and drag and drop TOC in and check frontend. It shows the question symbol in master.
- Switch to `table-of-content-replace-with-question-mark` and refresh the frontend and check again all is working fine or not.

Fix: Table of Contents - Heading replaced with the question symbol.

---

README.md
assets/js/table-of-contents.js
blocks-config/table-of-content/class-uagb-table-of-content.php
classes/class-uagb-loader.php
classes/class-uagb-scripts-utils.php
composer.json
composer.lock
package-lock.json
package.json
readme.txt
ultimate-addons-for-gutenberg.php

Release 1.23.1

---

README.md
classes/class-uagb-front-assets.php
readme.txt

[Trello ](https://trello.com/c/kHfenpPw/367-fix-add-max-width-to-the-section-to-avoid-full-width-sections)
Issue --> https://share.bsf.io/NQuoZXGr
non-breaking change which fixes an issue
Tested section full width on front-end.

Fix: Section - Full-Width issue on front-end.

---

README.md
assets/js/table-of-contents.js
blocks-config/table-of-content/class-uagb-table-of-content.php
readme.txt

- https://trello.com/c/2NjKOeA2/368-fix-table-of-contents-issue-displaying-some-german-persian-characters
- Test with Multiple Persian & German Strings.
- Also, check with other language strings, multiple other characters.
- Check Heading Scroll works or not.

fix: Table of Contents - Issue displaying some German & Persian characters.

---

README.md
classes/class-uagb-loader.php
package-lock.json
package.json
readme.txt
ultimate-addons-for-gutenberg.php

Update versions for v1.23.2.

---

README.md
assets/js/table-of-contents.js
blocks-config/table-of-content/class-uagb-table-of-content.php
readme.txt

Fixed: TOC utf8 encoding issue
https://share.bsf.io/geugw7DD

Fixed: TOC utf8 encoding issue

---

README.md
classes/class-uagb-admin.php
readme.txt

Issue - https://ua-gutenberg.atlassian.net/jira/software/projects/UAG/boards/2?selectedIssue=UAG-158
- Added test cases in the issue.

UAG-158 - Fix: Assets not regenerated for frontend when post conatining reusable blocks is updated.

---

.github/workflows/build-and-deploy.yml
Gruntfile.js

Sets up auto-deployment on staging server.
Improvement

Autodeployment setup

---

README.md
classes/class-uagb-admin.php
classes/class-uagb-rest-api.php
readme.txt

- Task - https://ua-gutenberg.atlassian.net/browse/UAG-308
- Added in the task.

Fix: Assets Generation issue on frontend when Twenty Twentyone theme is active.

---

admin/assets/common-block-editor.css
dist/build/blocks.asset.php

CSS for responsive icon

---

.github/workflows/build-a-zip.yml

Zip path and URL update & pointed to new server
New feature (non-breaking change which adds functionality)

Zip path and URL update & pointed to new server

---

.github/workflows/build-and-deploy.yml

Added common host key in action

Added common host key in action

---

classes/class-uagb-init-blocks.php
composer.lock

- Card - https://ua-gutenberg.atlassian.net/jira/software/projects/UAG/boards/2/backlog?selectedIssue=UAG-342
- Blocks of UAG should shows here - https://share.getcloudapp.com/QwuAXPPo

UAG-342 - Fix block_categories deprecated for register_block_category.

---

README.md
classes/class-uagb-front-assets.php
classes/class-uagb-post-assets.php
readme.txt

Task - https://ua-gutenberg.atlassian.net/jira/software/projects/UAG/boards/2?selectedIssue=UAG-348
Bug fix (non-breaking change which fixes an issue
- Added in the task.

UAG-348 - fix: Woocommerce shop page frontend styling gets removed when page is saved from editor.

---

classes/class-uagb-block-js.php
classes/class-uagb-rest-api.php

- Updated version x.x.x to 1.23.5

Update function version

---

dist/blocks-placeholder.js

Placeholder folder missing

---

admin/assets/admin-notice.css
admin/bsf-analytics/class-bsf-analytics.php
classes/class-uagb-admin.php

- https://brainstormforce.slack.com/archives/CAQ2TSA6A/p1626424872204200
- Classic editor notice 
- https://share.getcloudapp.com/jkuPNKe0
- https://share.getcloudapp.com/bLukPmgR
- 5 start ratings notice
- https://share.getcloudapp.com/P8u9Pev9
- https://share.getcloudapp.com/E0uAQzdE

UAG-355 Register the Astra Notices on `admin_init` action.

---

.github/workflows/update-version-and-build.yml

Manual trigger workflow to prepare a version and build update

Manual trigger workflow to prepare a version and build update

---

.github/workflows/update-version-and-build.yml

Fixed workflow error

---

.github/workflows/release-tag-draft.yml

Auto-create release tag in a draft

Auto create release tag in a draft

---

readme.txt

- Card - https://ua-gutenberg.atlassian.net/browse/UAG-360
- Check readme.

UAG-360 Updated star rating link and description in readme

---

classes/class-uagb-block-helper.php
dist/blocks.asset.php
dist/blocks.css
src/blocks/icon-list/editor.scss

- Card - https://ua-gutenberg.atlassian.net/browse/UAG-359
- Switch to the master
- Create a page with an Advanced column with 33/66 width and an Advanced heading with alignment left.
- Create a custom layout with an Advance column with 50/50 width and an Advanced heading with an alignment center.
- Set custom layout settings like this - https://share.getcloudapp.com/eDuy44JD
- Switch to the `uag-style-issue-with-custom-layout` , Regenerate the assets and check the page.
- Screencast - https://share.getcloudapp.com/7Kuo5KvR

UAG-359 Fix : Update CSS priority to resolve CSS conflict with custom layout and UAG blocks.

---

composer.lock
lib/gutenberg-templates/ast-block-templates.php
lib/gutenberg-templates/classes/class-ast-block-templates.php
lib/gutenberg-templates/version.json

- Card - https://ua-gutenberg.atlassian.net/browse/UAG-375
- Issue - https://d.pr/Yilh4g
- Switch to master open a customizer and check the console you will get the react console error from main.js
- Switch to `update-gutenberg-template-library` and refresh the customizer issue resolved.

UAG-375 Update Gutenberg template library

---

assets/js/table-of-contents.js
readme.txt

- Card - https://ua-gutenberg.atlassian.net/browse/UAG-368
- Drag and drop TOC.
- Copy hyperlink, Open it in firefox and safari browser.
- Check if hyperlinks scrolls to a specific heading or not.

UAG-368 Fix: Table of content - Hyperlink not working on safari and fire-fox browser.

---

.github/workflows/build-a-zip.yml

Delete zip workflow on PR merged

Delete zip workflow on PR merged

---

.github/workflows/build-a-zip.yml

Updated empty condition to remove a zip

---

dist/common-editor.css
src/blocks/demo-control-block/edit.js
src/common-editor.scss

fix: Added Responsive Icon, Units & Label alignment.
- Check Alignment.

fix: Added Responsive Icon, Units & Label alignment.

---

dist/blocks.asset.php
src/blocks/advanced-heading/styling.js
src/blocks/faq/styling.js
src/blocks/how-to/styling.js
src/blocks/info-box/inline-styles.js
src/blocks/section/styling.js
src/blocks/tabs/styling.js
src/blocks/wp-search/styling.js

- Updated missing single quotes due to which styling was not applying.
- All styling should be working fine in the editor.

Fix - Missing single quotes in styling JS.

---

admin-core/admin-loader.php
admin-core/ajax/ajax-base.php
admin-core/ajax/ajax-errors.php
admin-core/ajax/ajax-init.php
admin-core/ajax/common-settings.php
admin-core/api/api-base.php
admin-core/api/api-init.php
admin-core/api/common-settings.php
admin-core/inc/admin-helper.php
admin-core/inc/admin-menu.php
admin-core/inc/global-settings.php

Updated classes naming

---

.github/workflows/build-a-zip.yml

Build workflow updated

---

assets/js/faq.js
assets/js/forms.js
assets/js/post.js
assets/js/table-of-contents.js
assets/js/tabs.js
assets/js/timeline.js
assets/js/uagb-lottie.js

- JS Assets linting changes.
- Improvements
- Drag and drop the js specific blocks and check everything working properly or not.

Blocks Assest Linting

---

admin-core/assets/build/settings-app.asset.php
admin-core/assets/build/settings-app.css
admin-core/assets/build/settings-app.js
admin-core/assets/src/settings-app/components/blocks-page/BlocksSettings.js
admin-core/assets/src/settings-app/components/blocks-page/IndividualBlockSetting.js

Added state to manage ajax calls
non-breaking change which fixes an issue

Fix: Ajax call issues on blocks page

---

blocks-config/table-of-content/class-uagb-table-of-content.php
classes/class-uagb-loader.php
classes/class-uagb-twenty-seventeen-compatibility.php
dist/blocks.asset.php
package-lock.json
package.json
readme.txt
src/blocks/extensions/attributes.js
src/blocks/extensions/condition-block/index.js
src/blocks/marketing-button/attributes.js
src/blocks/marketing-button/deprecated.js
ultimate-addons-for-gutenberg.php

* Resolved display condition conflicting with wp-recipe block and gravity forms blocks
* Added fixes of the table of content empty li tag and marketing button validation issue

V1.25.1 (#1133)

---

classes/class-uagb-config.php

- Removed duplicate code.
- https://share.getcloudapp.com/NQux6L2z
- Improvement.

Improvement: Table of content - Duplicate code in asset config.

---

src/components/select-control/editor.lazy.scss
src/components/select-control/index.js

Added new UAGSelect Component. This component has an inline layout option.
New Features
Check components spacing color combination and prop types

New - UAGSelect component

---

classes/class-uagb-block-helper.php
includes/blocks/container/frontend.css.php

For border css generation and attribute generation
- New feature (non-breaking change which adds functionality)

Improvement: Added php functions for border component

---

includes/blocks/container/attributes.php
includes/blocks/container/frontend.css.php

Inner Container Flex Properties not applying.
- In the card.

SPCTR-1372 SPCTR-1374 - fix: Inner Container Flex Properties not applying & Row/Column Gap setting is not working.

---

README.md
readme.txt

Spelling for Lottie in changelog.

---

README.md
includes/blocks/icon-list/frontend.css.php
readme.txt

Fix: Icon List - Throws an PHP Notice for old users.

---

README.md
classes/class-uagb-block-helper.php
readme.txt

Border: Updated condition in border generation function

Border: Updated condition in border generation function

---

admin-core/inc/admin-menu.php
classes/class-uagb-init-blocks.php
classes/class-uagb-loader.php

Analytics fixes

---

README.md
classes/class-uagb-loader.php
includes/blocks/post-carousel/attributes.php
includes/blocks/post-masonry/attributes.php
package.json
readme.txt
ultimate-addons-for-gutenberg.php

Fix: Post Blocks - PHP notice if the number of columns are not set.

Fix: Post Blocks - PHP notice if the number of columns are not set.

---

README.md
classes/class-uagb-loader.php
readme.txt

- https://brainstormforce.atlassian.net/browse/SPCTR-1762
- NA
- Added in the card.

SPCTR-1762 Fix: Responsive condition - Conflicting with plugin using REST API block preview.

---

admin-core/inc/admin-menu.php
classes/class-uagb-init-blocks.php
classes/class-uagb-loader.php

Disable action scheduler until we find a fix for database related error

Analytics support - disabled action scheduler 

---

README.md
classes/class-uagb-loader.php
package.json
readme.txt
ultimate-addons-for-gutenberg.php

* Fix: Icon List - Bold/Italic style tag visible in aria-label attribute.
* Fix: Icon List - Text Alignment not working properly on front-end.
* Fix: Form - Backward Compatibility Stylings Issue on the editor.
* Fix: Advanced Column - Paragraph block wrapping with image when image size and position is changed.
* Fix: Advanced Column: Image was not getting aligned center on the frontend and the editor.
* Fix: Call To Action - Button css conflict with Newspaper theme.
* Fix: Customizer was frozen when theme blog settings were changed.
* Fix: Review Schema - Star ratings do not reflect on the frontend like the editor when multiple review blocks are used.
* Fix: Review Schema - Stars appear left in the editor and right on the frontend when clicked.
* Fix: Table of Contents - Adding …

Version PR: V2.0.13

---

includes/blocks/marketing-button/frontend.css.php

- https://brainstormforce.atlassian.net/browse/SPCTR-2024
- https://share.getcloudapp.com/6quGyLpz
- Added to the card.

SPCTR-2024 Fix: Marketing button - Hover issue on frontend in next-release only.

---

README.md
readme.txt

updated readme release version

---

classes/class-uagb-loader.php

Added Pro base loader hook

---

README.md
languages/ultimate-addons-for-gutenberg.pot
readme.txt

- WP-CLI
- Release date changed to 16th Nov 2022.
- NA
- NA
- NA

Release Date changed and WP-CLI command.

---

classes/class-uagb-init-blocks.php

- https://brainstormforce.atlassian.net/browse/SPCTR-2052
- https://share.getcloudapp.com/04uyb1jj 
- Drag and drop any block.
- Add a display condition.
- Verify whether it is working or not.

SPCTR-2052 Fix: Undefined `attrs` for Twenty Twenty Three Theme.

---

README.md
readme.txt

Updated Day to WEDNESDAY.

---

README.md
readme.txt

Updated the changelog of 2.0.16
N/A

Improvement: Updated Changelog for 2.0.16

---

README.md
includes/blocks/image-gallery/attributes.php
includes/blocks/image-gallery/block.php
includes/blocks/image-gallery/frontend.css.php
includes/blocks/image-gallery/frontend.js.php
readme.txt

Updated Changelog and Image Gallery Since Tags.

Merge: Spectra 2.1 Changelog and Image Gallery Minor Updates

---

classes/class-uagb-post-assets.php
languages/ultimate-addons-for-gutenberg.pot

- WP CLI CMD
- NA
- Improvement
- NA

WP CLI Command for Translation.

---

README.md
readme.txt

Updated and Rerorganized the 2 New Post Block Fixes in the Changelog.

Updated the Changelog for Spectra 2.1.1

---

README.md
classes/class-uagb-loader.php
package.json
readme.txt
ultimate-addons-for-gutenberg.php

* New: Introducing the Modal block that will help you to show your own customized popups on the page and turn your visitors into subscribers and leads!
* Improvement: Global - Added hover color accessibility to Spectra block with a button.
* Improvement: Counter - Bar Layout - Added toggle to flip/swap the positions of bar and title.
* Fix: Container - Resolved the issue where the list items overflow inside a Container on responsive devices.
* Fix: Image - Resolved the issue where the alignments are ineffective inside a Container on the front end.
* Fix: Buttons - Page scroll to the top when the hash link is added and refresh on click when the hash is removed.
* Fix: Tabs - Removed the WP default Link option from the toolbar for the tabs title field.
* Fix: Post Grid - Equal Height is not …

Updated Readme & Version

---

admin-core/ajax/common-settings.php
admin-core/inc/admin-menu.php
admin/bsf-analytics/class-bsf-analytics-stats.php
admin/bsf-analytics/class-bsf-analytics.php
blocks-config/forms/class-uagb-forms.php
blocks-config/image-gallery/class-spectra-image-gallery.php
blocks-config/lottie/class-uagb-lottie.php
blocks-config/post-timeline/class-uagb-post-timeline.php
blocks-config/post/class-uagb-post.php
blocks-config/table-of-content/class-uagb-table-of-content.php
blocks-config/taxonomy-list/class-uagb-taxonomy-list.php
classes/class-uagb-admin.php
classes/class-uagb-beta-updates.php
classes/class-uagb-helper.php
classes/class-uagb-init-blocks.php
classes/class-uagb-install.php
lib/gutenberg-templates/classes/class-ast-block-templates.php
phpcs.xml.dist

Fixing Wordpress-Vip-Go issues

SPCTR-2298 Wp-VIP-Go fixes

---

README.md
classes/class-uagb-block-module.php
classes/class-uagb-loader.php
package.json
readme.txt
ultimate-addons-for-gutenberg.php

Version Control PR v2.3.2

---

README.md
admin-core/inc/admin-menu.php
blocks-config/post/class-uagb-post.php
classes/class-uagb-loader.php
classes/class-uagb-post-assets.php
package.json
readme.txt
ultimate-addons-for-gutenberg.php

Php comment was added out of php boundary displaying in fronent.
WP Forum[ ticket ](https://wordpress.org/support/topic/post-grid-renders-comments-in-2-3-2/)

adding php comment properly

---

README.md
admin-core/inc/admin-menu.php
blocks-config/post/class-uagb-post.php
classes/class-uagb-loader.php
classes/class-uagb-post-assets.php
package.json
readme.txt
ultimate-addons-for-gutenberg.php

Release 2.3.3

---

blocks-config/forms/class-uagb-forms.php

- https://github.com/brainstormforce/ultimate-addons-for-gutenberg/pull/2698#discussion_r1094021454
- NA
- NA
- NA

if empty then continue check for forms.

---

classes/class-uagb-block-helper.php

- Reported by Mohit while testing a package.
- https://d.pr/v/d5IIIw
- https://share.getcloudapp.com/9Zuzp9OA
- https://share.getcloudapp.com/BluRAvly
- tested row/column gap.
- tested content padding.
- testing bottom margin.
- all the above settings were tested on responsive devices also.

Fix: Post block - A non-numeric value encountered issue for post block when adding content padding.

---

blocks-config/forms/class-uagb-forms.php

- Email fun() not working issue.

Forms to, from, cc, bcc and subject Email changes.

---

README.md
readme.txt

Changelog Updated.

---

src/blocks/inline-notice/attributes.js
src/blocks/inline-notice/block.js
src/blocks/inline-notice/deprecated.js
src/blocks/inline-notice/edit.js
src/blocks/inline-notice/editor.lazy.scss
src/blocks/inline-notice/render.js
src/blocks/inline-notice/save.js
src/blocks/inline-notice/settings.js
src/blocks/inline-notice/style.scss
src/blocks/inline-notice/styling.js
src/blocks/lottie/attributes.js
src/blocks/lottie/block.js
src/blocks/lottie/edit.js
src/blocks/lottie/render.js
src/blocks/lottie/settings.js
src/blocks/lottie/styling.js

Formatting of plugin using prettier.
**Script to format**: ` "lint-scripts:fix": "npm run pretty:fix && npm run lint-js -- --fix && npm run lint-css -- --fix",`
**Changes in .prettierrc.js:**
`config.overrides = [
{
files: [ '*.scss', '*.css', '*.js' ],
options: {
printWidth: 120,
singleQuote: true,
},
},
];`

SPCTR-2530: Improvement: Prettier-formatting

---

src/blocks/star-rating/attributes.js
src/blocks/star-rating/block.js
src/blocks/star-rating/deprecated.js
src/blocks/star-rating/edit.js
src/blocks/star-rating/editor.lazy.scss
src/blocks/star-rating/render.js
src/blocks/star-rating/save.js
src/blocks/star-rating/settings.js
src/blocks/star-rating/styling.js
src/blocks/table-of-contents/attributes.js
src/blocks/table-of-contents/block.js
src/blocks/table-of-contents/deprecated.js
src/blocks/table-of-contents/deprecated/components.js
src/blocks/table-of-contents/deprecated/table-of-contents.js
src/blocks/table-of-contents/deprecated/toc.js
src/blocks/table-of-contents/edit.js
src/blocks/table-of-contents/editor.lazy.scss
src/blocks/table-of-contents/render.js
src/blocks/table-of-contents/settings.js
src/blocks/table-of-contents/style.scss
src/blocks/table-of-contents/styling.js
src/blocks/table-of-contents/toc.js

Formatting of plugin using prettier.
**Script to format**: ` "lint-scripts:fix": "npm run pretty:fix && npm run lint-js -- --fix && npm run lint-css -- --fix",`
**Changes in .prettierrc.js:**
`config.overrides = [
{
files: [ '*.scss', '*.css', '*.js' ],
options: {
printWidth: 120,
singleQuote: true,
},
},
];`

SPCTR-2537: Improvement: Prettier formatting

---

readme.txt

Added a link in readme file

---

classes/class-uagb-front-assets.php
classes/class-uagb-post-assets.php
classes/class-uagb-rest-api.php

Empty check before is_array

---

.github/workflows/code-analysis.yml

Adding check for php 8.1 also in code analysis

adding check for php 8.1

---

blocks-config/post-timeline/class-uagb-post-timeline.php
blocks-config/post/class-uagb-post.php
blocks-config/taxonomy-list/class-uagb-taxonomy-list.php
classes/class-uagb-helper.php

WhiteList Allowed HTML Title Tags for Blocks.

---

admin-core/inc/admin-menu.php
classes/class-uagb-admin-helper.php
classes/class-uagb-admin.php

- Encryption decrytion of auth token.
- Updating required code.

SPCTR-3461 [Spec AI] Encryption decption of auth token
