src/blocks/column/block.js
src/blocks/columns/block.js

Hi,
I've just recently added Block Navigation toolbar on my [EditorsKit](https://wordpress.org/plugins/block-options/) plugin. I think this will be of great help on user navigation when both plugins are activated. The toolbar will only be shown on blocks with multiple inner blocks capability.
Here's how it works:
Let me know your thoughts.
Thanks,
Jeffrey

Add support for EditorsKit navigator toolbar

---

classes/class-uagb-helper.php
dist/blocks/post/index.php

Checked if the variable is set before using.
https://abhijitn-bsf.tinytake.com/tt/NDIyODk0OV8xMzIxNjk4NQ
No undefined errors

Checked if variable is set before using.

---

dist/blocks/post/index.php

Fixed - Pagination not working when using different permalink structures.
https://share.getcloudapp.com/xQuWvgLp
Bug fix (non-breaking change which fixes an issue) 
Check by changing the different Permalink structure if pagination works

Fixed - Pagination not working when using different permalink structure.

---

dist/blocks/post/index.php

Fixed: Next/Prev not visible in the editor issue.
https://imgur.com/Nmo1nth
Bug fix (non-breaking change which fixes an issue) 
Next/Prev visible in editor.

Fixed : Next/Prev not visible in editor issue.

---

dist/blocks.commoneditorstyle.build.css
readme.txt

Trello Task - https://trello.com/c/SLlU9Q3a/135-settings-get-disturbed-when-activated-gutenberg-plugin
https://imgur.com/fgyoJLh
Bugfix (non-breaking change which fixes an issue) 
Settings icon not overlapping when Gutenberg active.

Fix: Settings Icons overlapp on Label when Gutenberg plugin is activated. 

---

classes/class-uagb-helper.php
readme.txt

Fix: 404 error because of empty Font Family passed to link tag.
Bug fix (non-breaking change which fixes an issue) -
No error is console.

Fix: 404 error because of empty Font Family passed to link tag.

---

dist/blocks/post/index.php
readme.txt

Fix: Pagination not calculating Pages properly
Bugfix (non-breaking change which fixes an issue) 
Pagination Working Properly.
Post Per Page - 10.
Page Limit - 10
Total Posts - 10*10 = 100 in 10 pages 10 posts each.

Fix: Pagination not calculating Pages properly

---

classes/class-uagb-block-helper.php

Added Conditional padding for front-end.
Check whether padding is applying in front-end or not.

Added Conditional padding for front-end.

---

classes/class-uagb-block-helper.php

This PR fixes the warnings shown on the front page for some users. These users have created their site before the [Blocks migration](https://www.ultimategutenberg.com/control-child-items/).
The users who have never edited the page and migrated the blocks see this issue.
[Link](https://i.imgur.com/ic67zsU.png)
- Create Multi Buttons/ Social Share/ Icon List from v1.14.8
- Update to the latest version you will see PHP warnings on the frontend.
- Checkout to this branch the warnings will go away.

fix: PHP warnings for users who have built their site prior to v1.14.9 and never migrated the blocks.

---

classes/class-uagb-block-helper.php
readme.txt

Trello task - https://trello.com/c/gbEJBAjm
Check font size type for the label is applied to correctly or not

Fix: Icon List Font Size rendered as PX when configured as EM

---

classes/class-uagb-admin.php
classes/class-uagb-helper.php

Multiple files is being generated due to the incorrect passage of post id.
- Create a custom layout using Astra.
- Use UAG block in it.
- Refresh the page that fetches this layout.
- Unwanted files will be created under uag-plugin dir.

fix: Multiple file generation logic handled.

---

README.md
classes/class-uagb-block-helper.php
classes/class-uagb-helper.php
readme.txt

Trello - https://trello.com/c/9d6p9eiC/110-faqjs-is-not-needed-in-the-grid-layout
- Improvement
- Used faq grid layout and check is it loading `uagb-faq-js` .
- Used some other block-like timeline, testimonials and inline notice. Is this block working when the faq layout is the grid?
- Use both faqs as grid and accordion and check accordion is working or not.

Improvement: faq.js is not needed in the grid layout

---

README.md
dist/blocks/post-timeline/class-uagb-post-timeline.php
readme.txt

- Remove filter for the post timeline icon. 
- No test cases

Fix: Post Timeline - Removed filter for post timeline connector SVG.

---

assets/js/faq.js

- Trello - https://trello.com/c/mAYIj1q6/176-classlist-undefined-on-click-on-toc-heading-and-reload-page-from-faqjs 
- classList `undefined` issue when on click of toc heading and reload the page from faq.js
- Drag and drop Table of content and FAQ on page.
- Click on TOC heading and refresh the page on front-page. 
- Check console.

Added classlist undefined condition

---

README.md
assets/js/table-of-contents.js
readme.txt

- h_tag is not defined issue
- https://trello.com/c/EOWyiaqf/185-issue-of-toc-hyperlink-scroll-to-heading
- Breaking change

Fix: h_tag is not defined issue.

---

README.md
classes/class-uagb-config.php
dist/blocks/post/class-uagb-post.php
readme.txt

Trello - https://trello.com/c/ieHPjlAD/207-post-masonry-posttype-undefined-issue 
- Drag and drop masonry set pagination to Scroll or Load more.
- Visit frontend. scroll or click on load more and check the debug log.
- You will see the post_type undefined.
- Clear the debug log and Switch to this `post-type-undefined-in-masonry branch and refresh the page and check the debug log.

Fix: post masonry post_type undefined issue.

---

classes/class-uagb-update.php

Check upload dir permission and enabled asset file generation option in fresh setup
Non-breaking change
Install UAG plugin in fresh setup.
File generation should be enabled if the `wp-upload` folder is writable

Check upload dir permission and update asset generation option in fresh setup

---

lib/ast-block-templates/classes/class-ast-block-templates.php

- Trello - https://trello.com/c/Lzpnj7F6/318-fix-uag-template-pattern-categorie-label-not-visible-in-template-popup
- Check the same branch on a single site and multisite.
- If the label not visible then sync and refresh the page and try again

Fix Gutenberg template issue on multisite.

---

classes/class-uagb-init-blocks.php

- Tested on fresh setup with Toolset content template and WP Archive pages.
- Display deprecated PHP notices for uagb function and class name change.
- All is working fine.

Fix: Undefined index notice for disable blocks on fresh setup.

---

classes/class-uagb-helper.php

- While testing Astra Custom Layout  we get an issue `Invalid value supplied to an for each()`
- Created custom layout using Astra addon.
- Drag and drop blocks add styling and all is working fine.
- No issue and our deprecated notices for function and classes visible in debug log.

Fix deprecated function return nothing.

---

.eslintrc.js
src/blocks.js
webpack.config.js

- Webpack chunk breaking on Multisite and Sub folder domain and non-virtual cases due to static public path of the chunk.
- NA
- Added a public path dynamically.
- NA

fix: Webpack dynamic public path

---

blocks-config/post/class-uagb-post.php

The post meta link anchor tag was missing the `"`s around the URL causing HTML validation to fail.
Added the missing `"` characters around the URL.
Bug fix
Manually.

Fix invalid HTML markup in Post block

---

README.md
classes/class-uagb-front-assets.php
readme.txt

- Woocommece is installed and the current page is not from WooCOmmerce that's why it's throwing an issue. And It displays only on the first load.
- Added [changelog](https://github.com/brainstormforce/ultimate-addons-for-gutenberg/pull/713) for Invalid HTML markup of a post meta link.
- install the WooCommerce plugin.
- Visit any page which is not from WooCommerce.

Fix undefined `this_post` issue when Woocommece is install and the current page is not from WooCommerce.

---

dist/blocks.asset.php
webpack.config.js

PR - https://trello.com/c/VICNcebX/187-blocks-on-registered-when-kadence-blocks-plugin-is-active
- Check with the Kadence plugin active if our blocks get registered or not.

fix: Updated webpack configs to avoid conflicts with 3rd party plugins.

---

classes/class-uagb-scripts-utils.php

Fixed broken asset path when filename is empty

Fixed broken asset path when file name is empty

---

README.md
blocks-config/table-of-content/class-uagb-table-of-content.php
readme.txt

- Trello task - https://trello.com/c/PEX9IzXk/370-fix-table-of-contents-headings-with-other-tags-inside-them-are-not-visible-on-frontend
- Create Headings on a Page & Make the Bold/Italic/Strikethrough.
- Those headings should be visible on the front end.

Fix: Table of Contents: Headings with other tags inside them are not visible on frontend.

---

README.md
blocks-config/post/class-uagb-post.php
readme.txt

- Trello - https://trello.com/c/kVgHs8yS/369-fix-post-layout-excerpt-logic-broken-issue
- Add a post with post content and excerpt in the excerpt box in master.
- Drag and drop the post layout any and check front-end.  it will show post content in excerpt instead of excerpt box.
- Switch to  `post-layout-excerpt-issue` and check post layout it display correctly excerpt box content if added.

Fix: Post layout - Excerpt logic broken issue.

---

README.md
classes/class-uagb-post-assets.php
readme.txt

- Trello task - https://trello.com/c/sFmnbJlc/373-fix-posts-b7-displayed-in-place-of
- Added test case in the task.

Fix: Posts - "B7" displayed in place of " . " icon on frontend when file generation is disabled.

---

README.md
blocks-config/table-of-content/class-uagb-table-of-content.php
readme.txt

- Trello task - https://trello.com/c/LFFxwYKV/374-fix-table-of-contents
Bugfix (non-breaking change which fixes an issue
- Added in the task.

Fix: Table of Contents - Fatal error when $doc->documentElement is null in some cases on frontend.

---

README.md
classes/class-uagb-front-assets.php
readme.txt

- Trello task - https://trello.com/c/wvnWpTBW/379-fix-assets-generation-on-archive-pages-not-working-for-all-posts-on-frontend
- Create a post with some content and an immediate after content Icon list with the label.
- Visite customizer > Blog/archive > Post content > Full content.
- Go To reading > Your homepage displays > Your latest posts
- Check the Posts page. ( First Post Looks Okay, In other Icons are not visible )

Fix: Assets Generation on Archive Pages not working for all Posts on frontend.

---

README.md
classes/class-uagb-block-helper.php
readme.txt

- Trello - https://trello.com/c/B5IDxGO5/384-fix-advanced-column-shape-divider-issue-when-using-with-the-astra-custom-layout
- Added on Trello board.

Fix: Advanced column - Shape Divider issue when using with the Astra Custom Layout.

---

README.md
classes/class-uagb-block-js.php
classes/class-uagb-config.php
readme.txt

[Jira](https://ua-gutenberg.atlassian.net/browse/UAG-309)
Multiple blockquote blocks on the same page return the latest block content after clicking on tweet button.
- non-breaking change which fixes an issue
tested on Front-end.

Fix: Multiple blockquote post same content after tweet

---

README.md
blocks-config/table-of-content/class-uagb-table-of-content.php
readme.txt

Task - https://ua-gutenberg.atlassian.net/jira/software/projects/UAG/boards/2?selectedIssue=UAG-354
- Add Various Headings on a Page. ( H1 to H6 )
- Add 2 Table of Contents Blocks on a Page.
- Exclude different headings in both the Blocks.( https://d.pr/i/X9WcwD )
- Check on Frontend everything should work as expected.
- Add "uagb-toc-hide-heading" class in Advance Tab to any of the headings & see that the heading should be excluded on the frontend.

UAG-354 - Fix: Table of Contents - Headings not displayed properly when multiple Table of Contents blocks are added on same page.

---

dist/blocks.asset.php
src/blocks/star-rating/styling.js

- Star Rating > Stack > Alignment - not working in editor - https://vimeo.com/576686720/8034a2db15
- https://share.getcloudapp.com/Z4uKR5Dx

Fix Star rating alignment issue in editor when layout is stack.

---

classes/class-uagb-front-assets.php
readme.txt

Issue - https://wordpress.org/support/topic/1-23-5-update-conflict-with-wc-one-page-checkout-plugin/
- Install cartflows, create a flow, import any template.
- Go To the cartflows settings > set page builder as a Gutenberg
- Visit the checkout page. 
- Screencast of testing - https://share.getcloudapp.com/GGuWgkeD

Fix: Asset generation conflicts with WooCommerce pages.

---

assets/js/table-of-contents.js
readme.txt

- Card -https://ua-gutenberg.atlassian.net/browse/UAG-365
- Refrence - https://brainstormforce.slack.com/archives/CAQ2TSA6A/p1626940888042800
- Drag and drop Table of Contents on-page.
- Add styling to the block.
- Copy the hyperlink and open it in incognito mode and check scroll to heading in the new tab working fine or not.
- No deprecated notice no console error.

UAG-365 Fix: Table of contents - Uncaught TypeError with the load function.

---

admin/assets/common-block-editor.css
dist/blocks.asset.php

- Card - https://ua-gutenberg.atlassian.net/browse/UAG-364
- Check each and every responsive setting is clickable or not.
- Screencast - https://share.getcloudapp.com/Kou4PK9d

UAG-364 Fix: Responsive icon in tab not clickable issue.

---

classes/class-uagb-block-js.php
classes/class-uagb-config.php
readme.txt

- Card - https://ua-gutenberg.atlassian.net/browse/UAG-373
- Drag and drop Multiple blockquotes on page with different content.
- Visit the front end and click on the tweet button and check it redirected properly to specific blockquote or not.

UAG-373 Fix: Blockquote - Multiple blockquote post same content after clicking on tweet button.

---

classes/class-uagb-block-js.php
classes/class-uagb-post-assets.php

fix: Font does not load on frontend for Star Rating Block.
- Drop star rating 
- Apply font family on title
- Update & check on the front end
- In DOM it is showing font family

UAG-435 - fix: Font does not load on frontend for Star Rating Block.

---

classes/class-uagb-admin-helper.php

CF7 & GF styler CSS does not get added in the editor combined css file.
-  Test CF7 & GF Styler blocks.

fix: CF7 & GF styler CSS does not get added in the editor combined css file.

---

includes/blocks/tabs/frontend.css.php

- https://app.startinfinity.com/b/Mi5zu3VRVzk/M7Dpq9yR4Pe/789a120c-f15a-44c3-af94-9d577169bd5a?redirect=true&view=0ce18087-e6b2-4a91-b54c-c386ce1f811c&t=attributes
- Drag and drop Tabs
- Add an active text color and active bg color.
- Check by changing to a different layout.
- Check other settings like padding, margin and tyography.

Fix: Tabs - Active tabs color on frontend.

---

includes/blocks/container/attributes.php

- Default mobile content width for inner container 426.
- Drag and drop 2 layout containers.
- Add info-box in it.
- Publish and inspect the inner container and check content width is 426 or not.

Container : Default value for inner content custom width on mobile. 

---

includes/blocks/testimonial/attributes.php

Fixed Testimonial: Default Gradient background color not applying at frontend
Issue - https://www.awesomescreenshot.com/video/10337989?key=fde25537d18553f98da2df64dedefa8e
Fixed - https://share.getcloudapp.com/E0uy1N40
Bug fix (non-breaking change which fixes an issue) 
- Drag drop Testimonial block
- Set background color to gradient
- Do not change the gradient field values
- Save and check at frontend

SPCTR-1556 Testimonial: Default Gradient background color not applying at frontend

---

README.md
classes/class-uagb-front-assets.php
readme.txt

- Footer Widgets - CSS was not loading for empty archive/category and 404 pages. 
- For this bug to be recreated, we need to have some Spectra blocks in footer
- And also an empty category
- [JIRA](https://brainstormforce.atlassian.net/browse/SPCTR-1743)

SPCTR-1743 Footer Widgets - CSS was not loading for empty archive/category and 404 pages. 

---

lib/class-uagb-ast-block-templates.php

PHP Deprecated Notice from Gutenberg Templates library.
https://share.bsf.io/z8uQ14yw
New feature (non-breaking change which adds functionality)
- Check on PHP v8.1.9
- You will get a notice on admin pages.

fix: PHP Deprecated Notice from Gutenberg Templates library.

---

README.md
classes/class-uagb-loader.php
package.json
readme.txt
ultimate-addons-for-gutenberg.php

* Improvement: Highlight selected text on editor in Spectra blocks.
* Improvement: Responsive Conditions - Slanted lines are not visible in the editor.
* Improvement: Post Carousel/Masonry/Grid - Button text is now editable inside the editor.
* Improvement: Call To Action - CTA button text is now editable inside the editor.
* Improvement: Post Timeline - Button text is now editable inside the editor.
* Improvement: Info-Box - Add responsive feature in Info Box Icon width.
* Improvement: Call to Action: Added show icon toggle.
* Improvement: FAQ: Added background type selector for the question-answer container.
* Improvement: Forms: Added background type selector for submit button.
* Improvement: Info Box: Added background type selector for CTA.
* Improvement: Info Box: Added show icon …

Version Update: 2.0.15

---

includes/blocks/advanced-heading/attributes.php

Fix: Heading alignment is not working properly on the front-end
Heading - alignment stopped working on front -  https://share.bsf.io/2Nu6ALnz

SPCTR-2093 - Fix: Heading alignment not working properly on front-end

---

compatibility/class-uagb-astra-compatibility.php
readme.txt

- When Spectra gets activate, update the Astra menu position on top.
- Ref PR for Starter Templates - https://github.com/brainstormforce/astra-sites/pull/490
- With default position - https://share.getcloudapp.com/geuOdeAA
- With Spectra - https://share.getcloudapp.com/4gu4ZElA
- New feature (non-breaking change)
- Use this Astra 4.0 zip - https://share.getcloudapp.com/kpuO6kpG
- Once this zip installed you will get Astra menu on top of "Appearance"
- Once switched to this Spectra's branch Astra menu position gets updated at 2nd location.

chore: Astra 4.0 menu position updated next to dashboard on admin screen

---

classes/class-uagb-block-helper.php

- [Issue](https://github.com/brainstormforce/ultimate-addons-for-gutenberg/blob/master/classes/class-uagb-block-helper.php#L1617)
- https://d.pr/i/4ppykc
- Screencast of testing - https://share.getcloudapp.com/yAuA1Ok8
- Drag and drop any block which has a border style.
- Add a border style, width and radius on tablet, mobile and desktop.
- Verify it is applying as per set.
- Change unit of radius on desktop, tablet and mobile and verify as per unit radius is getting applied on  both end.

Fix border radius unit not working on mobile

---

src/blocks.js
src/common-editor.scss
src/components/text-shadow/editor.lazy.scss
src/components/text-shadow/index.js
src/components/typography/editor.lazy.scss
src/components/typography/font-typography.js
src/components/typography/fontloader.js
src/components/typography/index.js
src/components/typography/range-typography.js
src/styles/_variables.scss
src/styles/control-popup.scss
src/styles/gutenberg-override.scss

Formatting of plugin using prettier.
**Script to format**: ` "lint-scripts:fix": "npm run pretty:fix && npm run lint-js -- --fix && npm run lint-css -- --fix",`
**Changes in .prettierrc.js:**
`config.overrides = [
{
files: [ '*.scss', '*.css', '*.js' ],
options: {
printWidth: 120,
singleQuote: true,
},
},
];`

SPCTR-2547: Improvement: Prettier formatting

---

classes/class-uagb-block-helper.php
lib/uagb-webfont/uagb-webfont-loader.php

Updated PHP Explode Parameter Two Checks to ensure no null value passed in place of string.
Tested after regenerating assets in the front-end, as well as with matrix alignment for Image Gallery.

Fix: PHP Explode Parameter Two Handlers

---

README.md
classes/class-uagb-admin-helper.php
classes/class-uagb-loader.php
package.json
readme.txt
ultimate-addons-for-gutenberg.php

* Fix: Container - Updated default content width for block based themes to wideSize.

Spectra v2.4.2

---

README.md
blocks-config/post/class-uagb-post.php
readme.txt

Added Visibility Check for Carousels that Show Less Posts Per Page than Columns.
Tested as stated in [this comment](https://brainstormforce.atlassian.net/browse/SPCTR-2957?focusedCommentId=36313).

SPCTR-2957 - Hotfix: Post Carousel - Added Visibility Check for Carousels that Show Less Posts Per Page than Columns
